# Generated by Django 5.0.6 on 2024-06-12 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('RegistrationId', models.CharField(max_length=100)),
                ('Problem', models.TextField()),
                ('EmployeeAssigned', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PricePerHour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Amount', models.PositiveIntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('TicketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parts', to='api.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('ExpectedCost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Accepted', models.BooleanField(default=False)),
                ('Ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Estimate', to='api.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField(auto_now=True)),
                ('EndTime', models.DateTimeField(auto_now=True)),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TimeSlots', to='api.ticket')),
            ],
        ),
    ]
